# Generated by Django 2.2.11 on 2020-05-23 08:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('keypoints', django.contrib.postgres.fields.jsonb.JSONField()),
                ('descriptors', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
